swift_version: "4.0.0"
type: "vapor"

config:
    deploy:
        URL: ""
        TEAM_IDENTIFIER: ""
        APNS_AUTH_KEY_ID: ""
        APNS_AUTH_KEY_PATH: ""
        IDENTIFIER: ""
    all:
        URL: ""
        TEAM_IDENTIFIER: ""
        APNS_AUTH_KEY_ID: ""
        APNS_AUTH_KEY_PATH: ""
        IDENTIFIER: ""
